const SET_PRODUCTS = 'SET_PRODUCTS';
const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';

export const ActionTypes = {
  SET_PRODUCTS,
  SELECTED_PRODUCT,
  REMOVE_SELECTED_PRODUCT,
};

export default ActionTypes;
